# Generated by Django 4.2.3 on 2023-07-27 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=8)),
                ('details', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Prefered Name')),
                ('phone', models.CharField(max_length=10, verbose_name='Contact Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Contact Phone Number')),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed', models.FloatField(default=0.0)),
                ('paid', models.FloatField(default=0.0)),
                ('details', models.TextField(blank=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('crew_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.crew')),
                ('cupon_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.coupon')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.project')),
            ],
        ),
    ]
