# Generated by Django 4.2.3 on 2023-08-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_image_display_alter_print_display'),
        ('management', '0002_memeber'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='invoice',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='billing',
            name='project_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.project'),
        ),
        migrations.AlterField(
            model_name='memeber',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email Address'),
        ),
    ]
