# Generated by Django 4.2.3 on 2023-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_billing_invoice_alter_billing_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='fufiled',
            field=models.BooleanField(default=False),
        ),
    ]
