# Generated by Django 4.2.3 on 2023-08-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_billing_fufiled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField(auto_created=True)),
                ('amount', models.FloatField(default=5.0)),
                ('receipt', models.URLField(blank=True, max_length=400)),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.billing')),
            ],
        ),
    ]
