# Generated by Django 4.2.3 on 2023-08-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='details',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
