# Generated by Django 4.2.3 on 2023-08-31 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_payments_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0, max_length=8)),
                ('details', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='crew_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='details',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='details',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='details',
        ),
        migrations.AddField(
            model_name='billing',
            name='due_date',
            field=models.DateField(blank=True, default='2023-08-30'),
        ),
        migrations.AddField(
            model_name='billing',
            name='open_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payments',
            name='receipt',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.DeleteModel(
            name='Memeber',
        ),
        migrations.AddField(
            model_name='billing',
            name='credit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.credit'),
        ),
    ]
