# Generated by Django 4.2.3 on 2023-09-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_billing_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(default='due', max_length=30),
        ),
    ]
