# Generated by Django 4.2.3 on 2023-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_billing_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(blank=True, default='2023-09-28'),
        ),
    ]
