# Generated by Django 4.2.3 on 2023-10-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_billing_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(blank=True, default='2023-10-06'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(default='draft', max_length=30),
        ),
    ]
