# Generated by Django 4.2.3 on 2023-10-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_payments_payment_type_alter_billing_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(blank=True, default='2023-10-08'),
        ),
    ]
