# Generated by Django 4.2.3 on 2023-10-09 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_alter_projectevents_date'),
        ('management', '0031_alter_billing_due_date_alter_billing_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.project'),
        ),
    ]
