# Generated by Django 4.2.3 on 2023-10-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_billing_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='invoice',
            new_name='invoice_id',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='invoice_id',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='status',
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_type',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(default='draft', max_length=30),
        ),
    ]
