# Generated by Django 4.2.3 on 2023-10-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_rename_invoice_billing_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(blank=True, default='2023-10-10'),
        ),
    ]
