# Generated by Django 4.2.3 on 2023-10-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_alter_billing_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='details',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
