# Generated by Django 4.2.3 on 2023-07-27 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cost', models.FloatField(default=0.0)),
                ('details', models.TextField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, default=' ')),
                ('cloudflare_id', models.CharField(blank=True, max_length=255)),
                ('silk_id', models.CharField(default='CB01', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('image_link', models.URLField(blank=True, default=' ')),
                ('cloudflare_id', models.CharField(blank=True, max_length=255)),
                ('silk_id', models.CharField(default='CB01', max_length=50)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.project')),
            ],
        ),
    ]
