# Generated by Django 4.2.3 on 2023-07-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
