# Generated by Django 4.2.3 on 2023-08-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_image_disaply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='disaply',
            new_name='display',
        ),
    ]
