# Generated by Django 4.2.3 on 2023-08-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_disaply_image_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='display',
            field=models.CharField(choices=[('none', 'none'), ('home1', 'home1'), ('home2', 'home2'), ('home3', 'home3'), ('home4', 'home4'), ('gallery1', 'gallery1'), ('gallery2', 'gallery2'), ('project', 'project'), ('client', 'client')], default='none', max_length=20),
        ),
    ]
