# Generated by Django 4.2.3 on 2023-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_print_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='display',
            field=models.CharField(choices=[('none', 'none'), ('home1', 'home1'), ('home2', 'home2'), ('home3', 'home3'), ('home4', 'home4'), ('gallery1', 'gallery1'), ('gallery2', 'gallery2'), ('gallery3', 'gallery3'), ('gallery4', 'gallery4'), ('project', 'project'), ('client', 'client')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='print',
            name='display',
            field=models.CharField(choices=[('none', 'none'), ('home1', 'home1'), ('home2', 'home2'), ('home3', 'home3'), ('home4', 'home4'), ('gallery1', 'gallery1'), ('gallery2', 'gallery2'), ('gallery3', 'gallery3'), ('gallery4', 'gallery4'), ('project', 'project'), ('client', 'client')], default='none', max_length=20),
        ),
    ]
