# Generated by Django 4.2.3 on 2023-08-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_image_display_alter_print_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aspect',
            field=models.CharField(choices=[('1x1', '1x1'), ('3x2', '3x2'), ('4x3', '4x3'), ('16x9', '16x9')], default='none', max_length=20),
        ),
    ]
