# Generated by Django 4.2.3 on 2023-08-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_print_aspect_alter_image_aspect_alter_image_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='display',
            field=models.CharField(choices=[('none', 'none'), ('home1', 'home1'), ('home2', 'home2'), ('home3', 'home3'), ('home4', 'home4'), ('IOTM', 'IOTM'), ('gallery1', 'gallery1'), ('gallery2', 'gallery2'), ('gallery3', 'gallery3'), ('gallery4', 'gallery4'), ('subgal1', 'subgal1'), ('subgal2', 'subgal2'), ('subgal3', 'subgal3'), ('subgal4', 'subgal4'), ('project', 'project'), ('client', 'client')], default='portrait', max_length=20),
        ),
        migrations.AlterField(
            model_name='print',
            name='display',
            field=models.CharField(choices=[('none', 'none'), ('home1', 'home1'), ('home2', 'home2'), ('home3', 'home3'), ('home4', 'home4'), ('IOTM', 'IOTM'), ('gallery1', 'gallery1'), ('gallery2', 'gallery2'), ('gallery3', 'gallery3'), ('gallery4', 'gallery4'), ('subgal1', 'subgal1'), ('subgal2', 'subgal2'), ('subgal3', 'subgal3'), ('subgal4', 'subgal4'), ('project', 'project'), ('client', 'client')], default='none', max_length=20),
        ),
    ]
