# Generated by Django 4.2.3 on 2023-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_project_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deposit_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Pending Deposit', max_length=255),
        ),
    ]
