# Generated by Django 4.2.3 on 2023-09-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_billing_due_date'),
        ('gallery', '0013_project_deposit_amount_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(default='2023-09-17')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.project')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.payments')),
            ],
        ),
    ]
