# Generated by Django 4.2.3 on 2023-09-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_project_details_project_location_project_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectevents',
            old_name='Project_id',
            new_name='project_id',
        ),
        migrations.AlterField(
            model_name='projectevents',
            name='date',
            field=models.DateField(default='2023-09-21'),
        ),
    ]
