# Generated by Django 4.2.3 on 2023-09-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_billing_due_date'),
        ('gallery', '0016_rename_project_id_projectevents_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevents',
            name='event_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectevents',
            name='date',
            field=models.DateField(default='2023-09-23'),
        ),
        migrations.AlterField(
            model_name='projectevents',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.payments'),
        ),
    ]
