# Generated by Django 4.2.3 on 2023-09-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_projectevents_event_type_alter_projectevents_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='scope',
        ),
        migrations.AlterField(
            model_name='projectevents',
            name='date',
            field=models.DateField(default='2023-09-24'),
        ),
    ]
