# Generated by Django 4.2.3 on 2023-10-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_alter_projectevents_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevents',
            name='date',
            field=models.DateField(default='2023-10-09'),
        ),
    ]
