# Generated by Django 4.2.3 on 2023-10-10 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_alter_billing_due_date'),
        ('gallery', '0025_alter_image_display_alter_print_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectevents',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='projectevents',
            name='billing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.billing'),
        ),
        migrations.AlterField(
            model_name='projectevents',
            name='date',
            field=models.DateField(default='2023-10-10'),
        ),
    ]
