# Generated by Django 4.2.3 on 2023-07-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='project_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email Address'),
        ),
    ]
