# Generated by Django 4.2.3 on 2023-08-31 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_credit_remove_billing_client_id_and_more'),
        ('clients', '0003_remove_client_project_id_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='crew_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.crew'),
        ),
    ]
