# Generated by Django 4.2.3 on 2023-09-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_crew_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Prefered Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('hexkey', models.CharField(max_length=24)),
            ],
        ),
    ]
