# Generated by Django 4.2.3 on 2023-09-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='hexkey',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='invite',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
