# Generated by Django 4.2.3 on 2023-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_invite_hexkey_alter_invite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
