# Generated by Django 4.2.3 on 2023-09-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_1',
            field=models.CharField(default='none', max_length=255, verbose_name='Street Address/PO Box'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_2',
            field=models.CharField(default='none', max_length=255, verbose_name='Apt/Suite'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='none', max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_method',
            field=models.CharField(default='none', max_length=255, verbose_name=' - '),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default='none', max_length=255, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='client',
            name='zip_code',
            field=models.CharField(default='none', max_length=255, verbose_name='Zipcode'),
        ),
    ]
