# Generated by Django 4.2.3 on 2023-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_address_1_client_address_2_client_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_1',
            field=models.CharField(max_length=255, verbose_name='Street Address/PO Box'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_2',
            field=models.CharField(max_length=255, verbose_name='Apt/Suite'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_method',
            field=models.CharField(max_length=255, verbose_name=' - '),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(max_length=255, verbose_name='Zipcode'),
        ),
    ]
