# Generated by Django 4.2.3 on 2023-09-04 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0010_alter_client_address_1_alter_client_address_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('first_date', models.DateField(auto_now=True)),
                ('second_date', models.DateField(auto_now=True)),
                ('scope', models.CharField(max_length=255, verbose_name=' - ')),
                ('details', models.CharField(max_length=255, verbose_name='Street Address/PO Box')),
                ('location', models.CharField(max_length=255, verbose_name='Apt/Suite')),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
