# Generated by Django 4.2.3 on 2023-09-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_projectrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequest',
            name='first_date',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='second_date',
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='date',
            field=models.DateField(default='2023-09-04'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='details',
            field=models.CharField(max_length=3000, verbose_name='Project Details'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location type'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='scope',
            field=models.CharField(max_length=255, verbose_name='Project-Type/Scope'),
        ),
    ]
