# Generated by Django 4.2.3 on 2023-09-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_projectrequest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='1b4f', unique=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
