# Generated by Django 4.2.3 on 2023-09-06 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0015_alter_projectrequest_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='0992', unique=True),
        ),
        migrations.CreateModel(
            name='RequestReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=3000)),
                ('read', models.BooleanField(default=False)),
                ('project_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projectrequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
