# Generated by Django 4.2.3 on 2023-09-07 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0017_alter_projectrequest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='6dd1', unique=True),
        ),
        migrations.CreateModel(
            name='ProjectTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date1', models.CharField(max_length=10)),
                ('session_date2', models.CharField(blank=True, max_length=10)),
                ('session_date3', models.CharField(blank=True, max_length=10)),
                ('session_date4', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(max_length=255, verbose_name='Location type')),
                ('scope', models.CharField(max_length=255, verbose_name='Project-Type/Scope')),
                ('slug', models.SlugField(default='af14', unique=True)),
                ('project_cost', models.FloatField(default='600.00')),
                ('deposit', models.FloatField(default='0.00')),
                ('project_docs', models.CharField(max_length=255)),
                ('project_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.projectrequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
