# Generated by Django 4.2.3 on 2023-09-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_projectrequest_slug_projectterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectterms',
            name='services',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_end1',
            field=models.TimeField(blank=True, default='9:00', max_length=20),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_end2',
            field=models.TimeField(blank=True, default='9:00', max_length=20),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_end3',
            field=models.TimeField(blank=True, default='9:00', max_length=20),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_end4',
            field=models.TimeField(blank=True, default='9:00', max_length=20),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_start1',
            field=models.TimeField(blank=True, default='9:00', max_length=20),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_start2',
            field=models.TimeField(blank=True, default='9:00', max_length=20),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_start3',
            field=models.TimeField(blank=True, default='9:00', max_length=20),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_start4',
            field=models.TimeField(blank=True, default='9:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='95d6', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='scope',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='2c94', unique=True),
        ),
    ]
