# Generated by Django 4.2.3 on 2023-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_projectterms_services_projectterms_session_end1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectterms',
            name='city',
            field=models.CharField(default='greenville', max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectterms',
            name='state',
            field=models.CharField(default='NC', max_length=255, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectterms',
            name='zip',
            field=models.CharField(default='27855', max_length=7, verbose_name='Zip Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='588d', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Physical Address'),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='35b0', unique=True),
        ),
    ]
