# Generated by Django 4.2.3 on 2023-09-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_projectrequest_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='3ba4', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='deposit',
            field=models.IntegerField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='project_cost',
            field=models.IntegerField(default='600.00'),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='742b', unique=True),
        ),
    ]
