# Generated by Django 4.2.3 on 2023-09-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_alter_projectrequest_slug_alter_projectterms_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='ad3b', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='dd63', unique=True),
        ),
    ]
