# Generated by Django 4.2.3 on 2023-09-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_alter_projectrequest_slug_alter_projectterms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='d0b1', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_date2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_date4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_end1',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_end2',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_end3',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_end4',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_start1',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_start2',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_start3',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='session_start4',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='eed1', unique=True),
        ),
    ]
