# Generated by Django 4.2.3 on 2023-09-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_alter_projectrequest_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectterms',
            old_name='session_date1',
            new_name='session_date',
        ),
        migrations.RenameField(
            model_name='projectterms',
            old_name='session_end1',
            new_name='session_end',
        ),
        migrations.RenameField(
            model_name='projectterms',
            old_name='session_end2',
            new_name='session_start',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_date2',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_date3',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_date4',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_end3',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_end4',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_start1',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_start2',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_start3',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_start4',
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='543c', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='10bc', unique=True),
        ),
    ]
