# Generated by Django 4.2.3 on 2023-09-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_rename_session_date1_projectterms_session_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectterms',
            name='session_date2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_date3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_date4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_end2',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_end3',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_end4',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_start2',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_start3',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectterms',
            name='session_start4',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='105f', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='9736', unique=True),
        ),
    ]
