# Generated by Django 4.2.3 on 2023-09-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_projectterms_session_date2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectterms',
            name='city',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='location',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_date2',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_date3',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_date4',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_end2',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_end3',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_end4',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_start2',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_start3',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_start4',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='state',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='zip',
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='5588', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='a4a5', unique=True),
        ),
    ]
