# Generated by Django 4.2.3 on 2023-09-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_remove_projectterms_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='68a5', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='3165', unique=True),
        ),
    ]
