# Generated by Django 4.2.3 on 2023-09-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_alter_projectrequest_slug_alter_projectterms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='f1c6', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='deposit',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='project_cost',
            field=models.FloatField(default='600.00'),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='6068', unique=True),
        ),
    ]
