# Generated by Django 4.2.3 on 2023-09-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_alter_projectrequest_slug_alter_projectterms_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='strip_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='98f3', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='250e', unique=True),
        ),
    ]
