# Generated by Django 4.2.3 on 2023-09-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_alter_projectrequest_slug_alter_projectterms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='0b3a', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='b9ba', unique=True),
        ),
    ]
