# Generated by Django 4.2.3 on 2023-09-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_alter_projectrequest_slug_alter_projectterms_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectterms',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_end',
        ),
        migrations.RemoveField(
            model_name='projectterms',
            name='session_start',
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='9523', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='4def', unique=True),
        ),
    ]
