# Generated by Django 4.2.3 on 2023-09-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_remove_project_cost_remove_project_deposit_amount_and_more'),
        ('clients', '0041_remove_projectterms_session_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectterms',
            name='project_id',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='gallery.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='6714', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='7d0f', unique=True),
        ),
    ]
