# Generated by Django 4.2.3 on 2023-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_projectterms_project_id_alter_projectrequest_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='dcb2', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='ea0f', unique=True),
        ),
    ]
