# Generated by Django 4.2.3 on 2023-09-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_alter_projectrequest_slug_alter_projectterms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='bef7', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='dba2', unique=True),
        ),
    ]
