# Generated by Django 4.2.3 on 2023-09-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_alter_projectrequest_slug_alter_projectterms_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreply',
            name='date_posted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(default='c1ac', unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='845e', unique=True),
        ),
    ]
