# Generated by Django 4.2.3 on 2023-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_requestreply_date_posted_alter_projectrequest_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='01ab', unique=True),
        ),
    ]
