# Generated by Django 4.2.3 on 2023-10-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0051_alter_projectterms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='81c1', unique=True),
        ),
    ]
