# Generated by Django 4.2.3 on 2023-10-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_alter_projectterms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectterms',
            name='slug',
            field=models.SlugField(default='55d9', unique=True),
        ),
    ]
