# Generated by Django 4.2.3 on 2023-07-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='from_id',
            field=models.CharField(default='CONT', max_length=4),
        ),
    ]
